/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pertemuan_14;

/**
 *
 * @author Ridho
 */
import java.util.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.persistence.*;

public class InsertBooking extends javax.swing.JDialog {

    private DefaultTableModel model;
    private boolean saved = false;
    private Utama menuutama;
    

    // constructor utama (3 parameter)
    public InsertBooking(java.awt.Frame parent, boolean modal, Utama menuutama) {
        super(parent, modal);
        this.menuutama = menuutama;
        initComponents();
    }

    public boolean isSaved() {
        return saved;
    }

// Ambil data film dari textfield
    private void hilang() {
        cbLapangan.setSelectedIndex(0);
        tfTanggal.setText("");
        tfIdBooking.setText("");
        tfIdPelanggan.setText("");
        cbStatus.setSelectedIndex(0);
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InsertBooking.class.getName());

    /**
     * Creates new form InsertPengguna
     */
    public InsertBooking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInsertPelanggan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfTanggal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfIdPelanggan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfIdBooking = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbLapangan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("From Booking");

        jLabel3.setText("Lapangan");

        btnInsertPelanggan.setText("Insert");
        btnInsertPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPelangganActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Pending" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal");

        jLabel7.setText("Nama Pelanggan");

        tfIdPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdPelangganActionPerformed(evt);
            }
        });

        jLabel8.setText("Id Booking");

        tfIdBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdBookingActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        cbLapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lapangan A", "Lapangan B", "Lapangan C" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInsertPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfIdBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfIdPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfTanggal)
                                .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbLapangan, 0, 159, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfIdBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbLapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertPelanggan)
                    .addComponent(btnCancel))
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPelangganActionPerformed
        if (tfIdBooking.getText().isEmpty() || tfIdPelanggan.getText().isEmpty()
                || tfTanggal.getText().isEmpty() || cbLapangan.getSelectedItem() == null
                || cbStatus.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu!");
            return;
        }

        EntityManagerFactory emf = null;
        EntityManager em = null;

        try {
            int idb = Integer.parseInt(tfIdBooking.getText());
            String namaPelangganInput = tfIdPelanggan.getText().trim(); // ← SEKARANG NAMA, BUKAN ID
            String tgl = tfTanggal.getText();
            String lpng = (String) cbLapangan.getSelectedItem();
            String status = (String) cbStatus.getSelectedItem();

            emf = Persistence.createEntityManagerFactory("Pertemuan_14PU");
            em = emf.createEntityManager();
            em.getTransaction().begin();

            // =============================
            //   CARI ID BERDASARKAN NAMA
            // =============================
            Query qCari = em.createQuery(
                    "SELECT p FROM Pelanggan p WHERE LOWER(p.nama) = :nama"
            );
            qCari.setParameter("nama", namaPelangganInput.toLowerCase());

            List<Pelanggan> hasil = qCari.getResultList();

            if (hasil.isEmpty()) {
                JOptionPane.showMessageDialog(null,
                        "Nama pelanggan '" + namaPelangganInput + "' tidak ditemukan!");
                return;
            }

            Pelanggan idPelanggan = hasil.get(0);
            int idp = idPelanggan.getIdPelanggan(); // ← ID asli dari DB

            // =============================
            //   CEK BENTROK FULL-DAY
            // =============================
            String sqlCek = """
            SELECT COUNT(*) 
            FROM booking 
            WHERE lapangan = ? 
              AND tanggal = ?
        """;
            Query q = em.createNativeQuery(sqlCek);
            q.setParameter(1, lpng);
            q.setParameter(2, tgl);

            Number result = (Number) q.getSingleResult();
            if (result.intValue() > 0) {
                JOptionPane.showMessageDialog(null,
                        "Jadwal bentrok! Sudah ada booking di hari dan lapangan tersebut.",
                        "Jadwal Bentrok", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // =============================
            //          INSERT
            // =============================
            Booking b = new Booking();
            b.setIdBooking(idb);
            b.setIdPelanggan(idPelanggan); // ← kirim object pelanggan
            b.setTanggal(tgl);
            b.setLapangan(lpng);
            b.setStatus(status);

            em.persist(b);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Booking berhasil disimpan!");
            hilang();
            menuutama.showTableBooking();

        } catch (javax.persistence.PersistenceException ex) {

            // cek duplicate PK
            if (ex.getCause() instanceof org.eclipse.persistence.exceptions.DatabaseException
                    && ex.getCause().getCause() instanceof org.postgresql.util.PSQLException) {
                org.postgresql.util.PSQLException sqlEx
                        = (org.postgresql.util.PSQLException) ex.getCause().getCause();
                if (sqlEx.getSQLState().equals("23505")) {
                    JOptionPane.showMessageDialog(null,
                            "⚠️ ID Booking " + tfIdBooking.getText() + " sudah ada! Silakan ganti ID lain.",
                            "Duplicate ID", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID Booking harus angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        } finally {
            if (em != null) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                em.close();
            }
            if (emf != null) {
                emf.close();
            }
        }

        this.dispose();
    }//GEN-LAST:event_btnInsertPelangganActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void tfIdBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdBookingActionPerformed

    private void tfIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdPelangganActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsertPelanggan;
    private javax.swing.JComboBox<String> cbLapangan;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfIdBooking;
    private javax.swing.JTextField tfIdPelanggan;
    private javax.swing.JTextField tfTanggal;
    // End of variables declaration//GEN-END:variables
}
